### ISSUE TITLE
Try to debug typescript file

### ISSUE THREAD

**Issue by oshri** [whitecolor/ts-node-dev#9]
HI Dev,
I try to debug typescript files, in visual studio code.
to run the code I using yarn ts-node-dev server.

Need help :)

**configuration:**
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "port": 5858,
            "outFiles": []
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/server.ts",
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ],
            "cwd": "${workspaceRoot}"
        }
    ]
}

**error:**
Cannot connect to runtime; make sure that runtime is in 'legacy' debug mode.

**Comment by oshri** [comment]
When I add --inspect I get a weird error
command: yarn ts-node-dev --inspect server

<img width="1007" alt="screen shot 2018-03-12 at 11 32 55" src="https://user-images.githubusercontent.com/4602814/37275948-311dcaf2-25e9-11e8-9f17-3a712225ad9e.png">

**Comment by whitecolor** [comment]
does it work without `--inspect` flag?

**Comment by oshri** [comment]
No :(

**Comment by whitecolor** [comment]
Try to run it without debuger, then try to run it with just `ts-node` (not `ts-node-dev`), etc..

**Comment by francocorreasosa** [comment]
Same for me, but with `ts-node` I get the same result.

**Comment by Deilan** [comment]
So is there any way to make VS Code debug working or not? Looking for migrating from `nodemon` + `ts-node` to just `ts-node-dev`, but if there's no VS Code debug support, then I'd prefer to stay.

**Comment by Deilan** [comment]
Debug is working for me with the following configuration:
```json
{  
   "name":"Launch via nodemon",
   "type":"node",
   "request":"launch",
   "protocol":"inspector",
   "cwd":"${workspaceRoot}",
   "runtimeExecutable":"${workspaceRoot}/node_modules/.bin/ts-node-dev",
   "args":[  
      "${workspaceRoot}/src/index.ts"
   ],
   "restart":true
}
```

**Comment by oshri** [comment]
I found the solution that work for me.

Under .vscode ( folder ) you should create 2 files:
1. launch.json
2. tasks.json

**launch.json:**
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "Debug TypeScript in Node.js",
        "preLaunchTask": "typescript",
        "program": "${workspaceFolder}/src/index.ts",
        "cwd": "${workspaceFolder}",
        "protocol": "inspector",
        "outFiles": [
          "${workspaceFolder}/lib/**/*.js"
        ]
      }
    ]
  }

```

tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
      {
        "identifier": "typescript",
        "type": "typescript",
        "tsconfig": "tsconfig.json",
        "problemMatcher": [
          "$tsc"
        ]
      }
    ]
}

```

pacckage.json ( scripts section )
```
"scripts": {
    "start": "npm run build:live",
    "build:live": "NODE_ENV=development nodemon --exec  ./node_modules/.bin/ts-node -- ./src/index.ts --debug"
  }
```

To Run you should press Shift + command + B ( Tasks - > Run Build Task ).

**Comment by joseluisq** [comment]
Just **`ts-node-dev`** worked for me (no `nodemon` or VS code tasks) .

![screen shot 2018-12-07 at 10 49 39](https://user-images.githubusercontent.com/1700322/49640560-375b0c00-fa0e-11e8-8895-747b321cfcb5.png)

**Tools:**

- `VS Code`: v1.29.1
- `Node`: v10.6.0
- `ts-node-dev`: ^1.0.0-pre.31

**package.json**

```js
{
  "scripts": {
    "debug": "cross-env TZ=UTC NODE_ENV=development tsnd --inspect --respawn src/main.ts"
  }
}
```

**launch.json**

```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Typescript Server",
      // "processId": "${command:PickProcess}",
      "protocol": "inspector",
      "port": 9229,
      "restart": true,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "."
    }
  ]
}
```

**Usage:**

1. Run your debug NPM task: `npm run debug`
2. Start VS Code debugging.

**Comment by montera82** [comment]
@joseluisq thanks, this worked for me!

**Comment by joseluisq** [comment]
@montera82 if you want to debug in docker container check out: 
[Debugging TypeScript in a Docker Container](https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript)

Basically, it should works with minimal tweaks.

**Comment by gintsgints** [comment]
Works fine for me with this launch task:

```
    {
      "type": "node",
      "request": "launch",
      "name": "Launch server debug",
      "program": "${workspaceRoot}/node_modules/ts-node-dev/bin/ts-node-dev",
      "args": [
        "--inspect",
        "--no-notify",
        "--respawn",
        "--transpileOnly",
        "./src"
      ],
      "protocol": "inspector",
      "internalConsoleOptions": "openOnSessionStart",
      "port": 9229
    },
```

**Comment by stabback** [comment]
Expanding on @joseluisq's above - 

The solution nearly worked for me.  I'm unsure if it's because of my project settings, or if something in the dependencies have changed with time.

The above launch.json settings worked great to attach the debugger, however I found all of my breakpoints were appearing as `unverified breakpoint`.  I could log to the debugger, but couldn't  connect direct.

Removing `localRoot` and `remoteRoot` and specifying `cwd` allowed me to use breakpoints.

Updated instructions:

---
**Tools**
VS Code: v1.33.1
Node: v10.16.0
ts-node-dev: ^1.0.0-pre.40

**package.json**
```json
{
  ...
  "scripts": {
    ...
    "debug": "ts-node-dev --inspect --respawn --transpileOnly src/main.ts"
  },
  ...
}
```

**.vscode/launch.json**
```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Typescript Server",
        "protocol": "inspector",
        "port": 9229,
        "restart": true,
        "cwd": "${workspaceRoot}"
      }
    ]
  }
```

**Usage:**

1. Run your debug NPM task: npm run debug
2. Start VS Code debugging.

**Comment by M-Zuber** [comment]
@gintsgints I tried your solution as I don't want to have to manually run a command and then attach
but my breakpoints are not being hit

Have you run into this?

**Comment by gintsgints** [comment]
> @gintsgints I tried your solution as I don't want to have to manually run a command and then attach
> but my breakpoints are not being hit
> 
> Have you run into this?

No I have not. Check logs, may be somthing about port settings.

**Comment by alexbatis** [comment]
Leaving my launch.json file here for anyone who may find it useful:

`{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "ts-node-dev debug",
      "runtimeExecutable": "nodemon",
      "restart": true,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "sourceMaps": true,
      "smartStep": true,
      "args": [
        "--watch",
        "'src/**/*.ts'",
        "--ignore",
        "'src/**/*.spec.ts'",
        "--exec",
        "'ts-node-dev'",
        "-r",
        "tsconfig-paths/register",
        "<src/your_entry_point.ts>"
      ],
      "skipFiles": [
        "<node_internals>/**"
      ]
    }
  ]
}`

where _<src/your_entry_point.ts>_ is the entry point of your application.

This uses [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) to register custom paths registered in tsconfig.json.

if your app doesn't use this library, remove the lines :
`
  "-r",
  "tsconfig-paths/register",
`


I prefer this method as it doesn't require starting the application in a console then attaching the debugger on a seperate (vscode integrated) terminal.  It will both launch your application and attach the debugger - attaching all the breakpoints.

**Comment by mannok** [comment]
> @gintsgints I tried your solution as I don't want to have to manually run a command and then attach
> but my breakpoints are not being hit
> 
> Have you run into this?

Yes I have run into this...
Windows 10...

**Comment by sippeangelo** [comment]
Adding to this, currently VS Code seems to be having some issues reattaching. My program crashes with `EPIPE: broken pipe, write` as VS Code seems to be too slow to reattach on reload before my program starts writing output. I found the fix was to switch to `integratedTerminal` for the `console` option in launch.json instead of the default ~~`internalConsole`~~

This seems to be working for me so far:
```json
{
    "name": "ts-node-dev",
    "type": "node",
    "request": "launch",
    "protocol": "inspector",
    "cwd": "${workspaceRoot}",
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/ts-node-dev",
    "args": [
        "--inspect",
        "--no-notify",
        "--transpileOnly",
        "--respawn",
        "${workspaceRoot}/src"
    ],
    "console": "integratedTerminal",
    "restart": true
}
```

**Comment by davidzwa** [comment]
I had to add my `server.ts` after the last arg "${workspaceRoot}/src"

**Comment by Xaz16** [comment]
It is how it works for me now, with restart and registered paths from tsconfig.json.

Which troubles I resolved before I get this:

1. Error: ENAMETOOLONG: name too long -- when I use --transpileOnly option I get an error, but for now I can't reproduce this one. I used ts-node-dev without vscode debug just in bash.
2. node: bad option "--require tsconfig-paths/register" -- silly error without any info about how to resolve it, but it is a quite simple. Do not use it in args array in one element like `--require tsconfig-paths/register`, use it in 2 different elements `"--require", "tsconfig-paths/register"`
3. ECONNREFUSED -- in most cases with ts-node-dev lots of issues because you are trying to configure it through `runtimeExecutable` and `runtimeArgs`, but for me it works without any headache only if you combine `runtimeExecutable` and `args`

ts-node-dev debug config with typescript paths and auto reload:
```json
{
      "name": "Server tools",
      "type": "node",
      "request": "launch",
      "protocol": "inspector",
      "restart": true,
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/ts-node-dev",
      "cwd": "${workspaceFolder}/apps/server/tools/${input:toolName}",
      "internalConsoleOptions": "openOnSessionStart",
      "args": [
        "--inspect",
        "--respawn",
        "--no-notify",
        "--transpileOnly",
        "--require",
        "tsconfig-paths/register",
        "./src/main.ts"
      ]
}
```

@whitecolor as I can see lots of people comes to your lib after troubles with nodemon through this issue https://stackoverflow.com/a/50528031 and in most cases they trying to setup debugging. 

Would it be a good idea to put something like "troubleshooting" section to readme for such folks?

**Comment by rochapablo** [comment]
I'm getting `[ERROR] 15:37:43 SyntaxError: Cannot use import statement outside a module` but it does not show here's the problem.

It seems that it's when I try to import sequelize, but I can't see what I'm doing wrong.

**Comment by whitecolor** [comment]
@rochapablo probably trying to run some code that contains `import` inside node js

**Comment by filetvignon** [comment]
After an extensive amount of trial and error, this config seems to have worked for me:
```
{
  "console": "integratedTerminal",
  "internalConsoleOptions": "neverOpen",
  "name": "ts-node-dev",
  "restart": true,
  "request": "launch",
  "runtimeExecutable": "tsnd",
  "skipFiles": ["<node_internals>/**"],
  "type": "pwa-node",
  "runtimeArgs": ["--respawn"],
  "args": ["${workspaceFolder}/src/index.ts"]
}
```

**Comment by jehnls** [comment]
@joseluisq , Here it's works, it started normally , but I can't use break point.

Could someone help me please?

**Comment by MrMonotone** [comment]
This is what I used. The important part was making sure you pass the "--inspector" flag to ts-node-dev. e.g.
`ts-node-dev --inspect --files src/index`
My file for reference.
`
        {
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "protocol": "inspector",
        }
`
There is also the auto attach feature you can look at. Check here:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach
I still needed to pass in the --inspect flag to get it working though. I was using lerna so that might be an issue.
After a few hours of googling hopefully this will help more people.
