### ISSUE TITLE
Default NODE_ENV

### ISSUE THREAD

**Issue by DimaIT** [whitecolor/ts-node-dev#91]
In my application I had logic that set `NODE_ENV` to `"local"` if it wasn't set before. So I was able to start application without `NODE_ENV` and it worked fine.

Now I'm trying to switch to typescript with ts-node-dev. And I've faced that ts-node-dev sets `NODE_ENV` to `development`:

https://github.com/whitecolor/ts-node-dev/blob/3529f8ead6ae8e02353f4a877073645e0a2338e9/lib/wrap.js#L18

That breaks my application.

1. Is it possible to disable default `NODE_ENV` behavior?
2. Is it possible to set default `NODE_ENV` to value other than `development`?
3. I was not able to find anything about default `NODE_ENV` behavior in docs, is it present anywhere?

**Comment by whitecolor** [comment]
For dev convenience. Usually, env is set anyway somehow for the running app. As for your question, this behvaiour is not a subject for change. You have to consider it.

**Comment by mpvosseller** [comment]
@whitecolor I ran into this too. Would you accept a PR that adds a command line argument to disable setting `NODE_ENV`? Maybe call it `--ignore-node-env`? Nothing change for most people but gives devs the option to disable this behavior.

Context: on my local machine I use `dotenv` to load environment variables (including `NODE_ENV`) as the application starts from a `.env` file.  This works great with `ts-node` and `node` but breaks with `ts-node-dev`. When `ts-node-dev` starts it sets `NODE_ENV` to `development` and then as the application starts `dotenv` doesn't set `NODE_ENV` because it sees it was set by someone else.

**Comment by Bejasc** [comment]
+1 for an optional flag to disable the node-env behaviour

@whitecolor is this something that can be considered? My context is the same as @mpvosseller

**Comment by whitecolor** [comment]
Yes, removed it, should be set explicitly by the user.

**Comment by mpvosseller** [comment]
@Bejasc One workaround I used is to run `ts-node-dev` with `-r dotenv/config`. As described in the [dotenv documentation](https://github.com/motdotla/dotenv#preload):

> You can use the --require (-r) command line option to preload dotenv. By doing this, you do not need to require and load dotenv in your application code. This is the preferred approach when using import instead of require

If you do that and set `NODE_ENV` in your `.env` file it does get picked up in `ts-node-dev`.

**Comment by Bejasc** [comment]
In my case, I actually figured out that node will take the env file fro.
The directory you're calling the command from, not the directory of the
file you're running through node.

**Comment by whitecolor** [comment]
As I said, I removed it and already published updated version, you may try.
